import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { outfit } from "./library/font";

export const metadata: Metadata = {
  title: "FormForge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.className} brightness-90`}>
      <body>
        {children}
        <Toaster position="top-right" />
      </body>
    </html >
  );
}
