name: Deploying app to vercel

on:
  push:
    branches:
      - revamp/applify

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install
        
      - name: Generate prisma client
        run: pnpx prisma generate

      - name: Install Vercel CLI
        run: pnpm install -g vercel
      
      - name: Deploy to vercel.
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
        run: |
          vercel --token $VERCEL_TOKEN \
          --prod \
          --yes 